### ISSUE TITLE
Styling af admin interface

### ISSUE THREAD

**Issue by neic** [TK-IT/web#40]
- [ ] Ny app med subclass af AdminSite [Doc](https://docs.djangoproject.com/en/1.8/ref/contrib/admin/#customizing-the-adminsite-class)
- [ ] Verbose names på fields
- [ ] tk-brand hjælp på flatpages #77 
- [ ] Tilføj css:

``` css
input[readonly=true] {
  color: #888;
}
```
